spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/semantic_analyze
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: db.changelog/db.changelog-master.yaml
server:
  port: 8888
semantic-analyze:
  properties:
    jwt:
      secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"